/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reinas.vista;

import reinas.modelo.Casilla;
import reinas.modelo.Estado;

/**
 *
 * @author Fernando
 */
public class FrmTablero extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmTablero() {
        initComponents();
        inicializarCasillas();
        //prueba de ejemplo
//        Casillas[0][1].chanceEstado(Estado.OCUPADO);
//        Casillas[2][2].chanceEstado(Estado.OCUPADO);
        

    }

    public Casilla[][] getCasillas() {
        return Casillas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        tablero1 = new javax.swing.JLabel();

        tablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MiniTablero.jpg"))); // NOI18N
        tablero.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 40));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 40, 40));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 40, 40));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 40, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 40, 40));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 40, 40));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 40, 40));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 40, 40));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 40));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 40, 40));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 40, 40));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 40, 40));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 40, 40));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 40, 40));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 40, 40));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 40, 40));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 40, 40));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 40, 40));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 40));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 40, 40));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 40, 40));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 40, 40));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 40, 40));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 40, 40));
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 40, 40));
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 40, 40));
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, 40));
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 40, 40));
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 40, 40));
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 40, 40));
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 40, 40));
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 40, 40));
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 40));
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 40, 40));
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 40, 40));
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 40, 40));
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 40, 40));
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 40, 40));
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 40, 40));
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 40));
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 40, 40));
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 40, 40));
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, 40));
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 40, 40));
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 40, 40));
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 40, 40));
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 40, 40));
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 40, 40));
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 40, 40));
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 40, 40));
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 40, 40));
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 40, 40));
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 40, 40));
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 40, 40));
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 40, 40));
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 40, 40));
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 40, 40));
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 40, 40));
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 40, 40));
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 40, 40));
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 40, 40));
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 40, 40));
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 40, 40));

        tablero1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MiniTablero.jpg"))); // NOI18N
        tablero1.setText("jLabel1");
        getContentPane().add(tablero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel tablero;
    private javax.swing.JLabel tablero1;
    // End of variables declaration//GEN-END:variables

    private Casilla[][] Casillas = new Casilla[8][8];

    private void inicializarCasillas() {
        Casillas[0][0] = new Casilla(jLabel1);
        Casillas[0][1] = new Casilla(jLabel2);
        Casillas[0][2] = new Casilla(jLabel3);
        Casillas[0][3] = new Casilla(jLabel4);
        Casillas[0][4] = new Casilla(jLabel5);
        Casillas[0][5] = new Casilla(jLabel6);
        Casillas[0][6] = new Casilla(jLabel7);
        Casillas[0][7] = new Casilla(jLabel8);
        Casillas[1][0] = new Casilla(jLabel9);
        Casillas[1][1] = new Casilla(jLabel10);
        Casillas[1][2] = new Casilla(jLabel11);
        Casillas[1][3] = new Casilla(jLabel12);
        Casillas[1][4] = new Casilla(jLabel13);
        Casillas[1][5] = new Casilla(jLabel14);
        Casillas[1][6] = new Casilla(jLabel15);
        Casillas[1][7] = new Casilla(jLabel16);
        Casillas[2][0] = new Casilla(jLabel17);
        Casillas[2][1] = new Casilla(jLabel18);
        Casillas[2][2] = new Casilla(jLabel19);
        Casillas[2][3] = new Casilla(jLabel20);
        Casillas[2][4] = new Casilla(jLabel21);
        Casillas[2][5] = new Casilla(jLabel22);
        Casillas[2][6] = new Casilla(jLabel23);
        Casillas[2][7] = new Casilla(jLabel24);
        Casillas[3][0] = new Casilla(jLabel25);
        Casillas[3][1] = new Casilla(jLabel26);
        Casillas[3][2] = new Casilla(jLabel27);
        Casillas[3][3] = new Casilla(jLabel28);
        Casillas[3][4] = new Casilla(jLabel29);
        Casillas[3][5] = new Casilla(jLabel30);
        Casillas[3][6] = new Casilla(jLabel31);
        Casillas[3][7] = new Casilla(jLabel32);
        Casillas[4][0] = new Casilla(jLabel33);
        Casillas[4][1] = new Casilla(jLabel34);
        Casillas[4][2] = new Casilla(jLabel35);
        Casillas[4][3] = new Casilla(jLabel36);
        Casillas[4][4] = new Casilla(jLabel37);
        Casillas[4][5] = new Casilla(jLabel38);
        Casillas[4][6] = new Casilla(jLabel39);
        Casillas[4][7] = new Casilla(jLabel40);
        Casillas[5][0] = new Casilla(jLabel41);
        Casillas[5][1] = new Casilla(jLabel42);
        Casillas[5][2] = new Casilla(jLabel43);
        Casillas[5][3] = new Casilla(jLabel44);
        Casillas[5][4] = new Casilla(jLabel45);
        Casillas[5][5] = new Casilla(jLabel46);
        Casillas[5][6] = new Casilla(jLabel47);
        Casillas[5][7] = new Casilla(jLabel48);
        Casillas[6][0] = new Casilla(jLabel49);
        Casillas[6][1] = new Casilla(jLabel50);
        Casillas[6][2] = new Casilla(jLabel51);
        Casillas[6][3] = new Casilla(jLabel52);
        Casillas[6][4] = new Casilla(jLabel53);
        Casillas[6][5] = new Casilla(jLabel54);
        Casillas[6][6] = new Casilla(jLabel55);
        Casillas[6][7] = new Casilla(jLabel56);
        Casillas[7][0] = new Casilla(jLabel57);
        Casillas[7][1] = new Casilla(jLabel58);
        Casillas[7][2] = new Casilla(jLabel59);
        Casillas[7][3] = new Casilla(jLabel60);
        Casillas[7][4] = new Casilla(jLabel61);
        Casillas[7][5] = new Casilla(jLabel62);
        Casillas[7][6] = new Casilla(jLabel63);
        Casillas[7][7] = new Casilla(jLabel64);
    }

}
